db.movies.insert(
    [
     {"name": "GREEN BOOK"},
     {"name": "THE SHAPE OF WATER"},
     {"name": "MOONLIGHT"},
     {"name": "SPOTLIGHT"},
     {"name": "BIRDMAN"},
     {"name": "12 YEARS A SLAVE"},
     {"name": "ARGO"},
     {"name": "THE ARTIST"},
     {"name": "THE KING'S SPEECH"},
     {"name": "THE HURT LOCKER"},
     {"name": "SLUMDOG MILLIONAIRE"},
     {"name": "NO COUNTRY FOR OLD MEN"},
     {"name": "THE DEPARTED"},
     {"name": "CRASH"},
     {"name": "MILLION DOLLAR BABY"},
     {"name": "THE LORD OF THE RINGS: THE RETURN OF THE KING"},
     {"name": "CHICAGO"},
     {"name": "A BEAUTIFUL MIND"},
     {"name": "GLADIATOR"},
     {"name": "AMERICAN BEAUTY"},
     {"name": "SHAKESPEARE IN LOVE"},
     {"name": "TITANIC"},
     {"name": "THE ENGLISH PATIENT"},
     {"name": "BRAVEHEART"},
     {"name": "FORREST GUMP"},
     {"name": "SCHINDLER’S LIST"},
     {"name": "UNFORGIVEN"},
     {"name": "THE SILENCE OF THE LAMBS"},
     {"name": "DANCES WITH WOLVES"},
     {"name": "DRIVING MISS DAISY"},
     {"name": "RAIN MAN"},
     {"name": "THE LAST EMPEROR"},
     {"name": "PLATOON"},
     {"name": "OUT OF AFRICA"},
     {"name": "AMADEUS"},
     {"name": "TERMS OF ENDEARMENT"},
     {"name": "GANDHI"},
     {"name": "CHARIOTS OF FIRE"},
     {"name": "ORDINARY PEOPLE"},
     {"name": "KRAMER VS. KRAMER"},
     {"name": "THE DEER HUNTER"},
     {"name": "ANNIE HALL"},
     {"name": "ROCKY"},
     {"name": "ONE FLEW OVER THE CUCKOO'S NEST"},
     {"name": "THE GODFATHER PART II"},
     {"name": "THE STING"},
     {"name": "THE GODFATHER"},
     {"name": "THE FRENCH CONNECTION"},
     {"name": "PATTON"},
     {"name": "MIDNIGHT COWBOY"},
     {"name": "OLIVER!"},
     {"name": "IN THE HEAT OF THE NIGHT"},
     {"name": "A MAN FOR ALL SEASONS"},
     {"name": "THE SOUND OF MUSIC"},
     {"name": "MY FAIR LADY"},
     {"name": "TOM JONES"},
     {"name": "LAWRENCE OF ARABIA"},
     {"name": "WEST SIDE STORY"},
     {"name": "THE APARTMENT"},
     {"name": "BEN-HUR"},
     {"name": "GIGI"},
     {"name": "THE BRIDGE ON THE RIVER KWAI"},
     {"name": "AROUND THE WORLD IN 80 DAYS"},
     {"name": "MARTY"},
     {"name": "ON THE WATERFRONT"},
     {"name": "FROM HERE TO ETERNITY"},
     {"name": "THE GREATEST SHOW ON EARTH"},
     {"name": "AN AMERICAN IN PARIS"},
     {"name": "ALL ABOUT EVE"},
     {"name": "ALL THE KINGS MEN"},
     {"name": "HAMLET"},
     {"name": "GENTLEMAN'S AGREEMENT"},
     {"name": "THE BEST YEARS OF OUR LIVES"},
     {"name": "THE LOST WEEKEND"},
     {"name": "GOING MY WAY"},
     {"name": "CASABLANCA"},
     {"name": "MRS. MINIVER"},
     {"name": "HOW GREEN WAS MY VALLEY"},
     {"name": "REBECCA"},
     {"name": "GONE WITH THE WIND"},
     {"name": "YOU CAN'T TAKE IT WITH YOU"},
     {"name": "THE LIFE OF EMILE ZOLA"},
     {"name": "THE GREAT ZIEGFELD"},
     {"name": "MUTINY ON THE BOUNTY"},
     {"name": "IT HAPPENED ONE NIGHT"},
     {"name": "CAVALCADE"},
     {"name": "GRAND HOTEL"},
     {"name": "CIMARRON"},
     {"name": "ALL QUIET ON THE WESTERN FRONT"},
     {"name": "THE BROADWAY MELODY"},
     {"name": "WINGS"} 
     ]
 )
 